### PR TITLE
31027 initial style guide

### PR DESCRIPTION
**Pull request by JohnAlbin**
Add screenshots and description.

### CODE REVIEW

**Comment by nickschuch** [comment]
test this please

**Comment by nickschuch** [comment]
Im seeing this on both types of builds:

```
You are about to CREATE  the 'agov_test' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a few seconds ...           [ok]
WD php: PDOException: SQLSTATE[23000]: Integrity constraint          [error]
violation: 1062 Duplicate entry
'agov_whitlam-search_api_page-default_search' for key 'tmd': INSERT
INTO {block} (module, delta, theme, title, status, weight, region,
visibility, pages, cache) VALUES (:db_insert_placeholder_0,
```

**Comment by kimpepper** [comment]
That's weird. Nothing in this PR has to do with installer.

**Comment by kimpepper** [comment]
test this please

**Comment by nickschuch** [comment]
test this please

**Comment by kimpepper** [comment]
test this please

**Comment by kimpepper** [comment]
Good to merge :+1:

**Comment by JohnAlbin** [comment]
Yes, we will need to update the old agov_zen and strip out all the CSS, but I don't see any reason to remove it and start over.

**Comment by JohnAlbin** [comment]
test this please

**Comment by JohnAlbin** [comment]
Some really interesting changes here. Merging!

**Comment by kimpepper** [comment]
Woohoo!

**Pull request merged**
