### PR TITLE
[#32429] Themed nested footer menu

### PR DESCRIPTION
**Pull request by lena40**
Check secondary footer menu looks as follows:
[](https://dl.dropbox.com/s/whwb0fqacb25kho/Screenshot%202015-07-23%2017.58.16.png?dl=0)

### CODE REVIEW

**Comment by kimpepper** [comment]
footer

**Comment by lena40** [comment]
@kimpepper should be fixed now.

**Comment by kimpepper** [comment]
Hmmm. This is causing weird spacing issues.
screen shot 2015-07-24 at 8 59 19 am

**Comment by lena40** [comment]
@kimpepper Yep, that is what it looks currently. . Will take a quick look.

**Pull request merged**
