### PR TITLE
31031 grouping element styling

### PR DESCRIPTION
**Pull request by HierenFeb**
Please check  #31031 grouping element style

Style guide is here: https://agov_pr480.agov.com.au/styleguide/agov_whitlam/section-base.html#kssref-base-grouping

### CODE REVIEW

**Comment by JohnAlbin** [comment]
I fixed a merge conflict.

**Comment by JohnAlbin** [comment]
I also fixed a bug that I just fixed in Zen 7.x-6.x-dev.

Only thing to fix is: blockquotes shouldn't have left/right margins.

**Comment by HierenFeb** [comment]
@JohnAlbin  I removed left/right margins of blockquotes. Please check!

**Comment by JohnAlbin** [comment]
Looks good!

**Comment by joannguyen** [comment]
Hi Feb, please fix margin in ul, ol.
and style for hr tag same hard rule style in https://redmine.previousnext.com.au/issues/31084

**Comment by HierenFeb** [comment]
Updated list and hr style, @joannguyen  Please check it!

**Comment by JohnAlbin** [comment]
Ha! Okay. I forgot to push a fix form Zen 7.x-6.x. Let me fix.

**Comment by JohnAlbin** [comment]
Looks good to me now. :-)

**Pull request merged**
