### PR TITLE
#34816: Remove D7-isms (like many fugly selectors) from Whitlam

### PR DESCRIPTION
**Pull request by rcaracaus**

### CODE REVIEW

**Comment by rcaracaus** [comment]
The purpose of this Pull request is to ensure that there are no Drupal 7 selectors in our Drupal 8 implementation of agov. I think a better approach would to remove all components and pull them in manually as we complete functional, testable stories rather than waterfalling through all of these components. There are components in here I think we may not need, like watermark and autocomplete. Anyway, this commit will at least ensure there are no extra fugly selectors.

**Comment by rcaracaus** [comment]
I have created https://redmine.previousnext.com.au/issues/34847 to document the need to actually go through each of these components and map them to Drupal 8 provided core classes. This is going to take over 6 hours I think so def warrants a new story and we should be QAing these components individually with steps to test to confirm they work and to spread around the knowledge that they exist.

**Comment by JohnAlbin** [comment]
test this please

**Comment by benjy** [comment]
I wish every patch had this much red! :)

**Comment by Sam152** [comment]
test this please

**Pull request merged**
