### PR TITLE
[WIP] Adds htmlcs module.

### PR DESCRIPTION
**Pull request by nickschuch**
**WIP**
* Testing install profile
* Requires theming

### CODE REVIEW

**Comment by xtfer** [comment]
Travis error may be spurious.

**Comment by nickschuch** [comment]
They are legit fails, working on it.

**Comment by kimpepper** [comment]
That PR environment doesn't look right....
screen shot 2015-01-30 at 3 39 23 pm

**Comment by nickschuch** [comment]
WIP everyone :)

**Comment by kimpepper** [comment]
test this please

**Comment by nickschuch** [comment]
Thanks for rebuilding :)

**Comment by kimpepper** [comment]
Current issues are:

- Hides behind Panels IPE toolbar
- Doesn't appear on some pages (appears briefly then disappears?)

htmlcs

**Comment by kimpepper** [comment]
Test on Firefox (due to ssl redirect issue on chrome)

**Comment by nickschuch** [comment]
Ill be theming this too look more like the original one we had as well. Hoping that will help as well.

**Comment by kimpepper** [comment]
Needs a couple of patches committed and a version bump.

**Comment by kimpepper** [comment]
test this please

**Comment by kimpepper** [comment]
@nickschuch Needs a review now it's building properly.

**Comment by kimpepper** [comment]
Needs to be rebased on 7.x-3.0

**Comment by kimpepper** [comment]
See #469

**Pull request closed without merging**
