### PR TITLE
Build system 3.x

### PR DESCRIPTION
**Pull request by nickschuch**
Same as https://github.com/previousnext/agov/pull/461 but for 3.x

### CODE REVIEW

**Comment by kimpepper** [comment]
I'm getting permissions issues: 

```
Unable to unzip /tmp/make_tmp_1429922519_553ae2d7d69fc/chosen_v1.1.0.zip.                                    [error]
```

**Comment by nickschuch** [comment]
Nope, those are because unzip isn't installed on the VM. Pushed a temp fix. https://github.com/previousnext/agov/commit/ef3871072619014d5ff29a1c892d19e52db9ba15

**Comment by kimpepper** [comment]
Added a PR to the vagrant box build repo https://github.com/previousnext/pnx-dev/pull/2

**Comment by nickschuch** [comment]
I have:
* Rolled a new version of the development box (0.0.3), you can update with `vagrant box update`
* Rolled back the unzip changes.

Steps to test:
* `vagrant box update` will update the box.
* `vagrant destroy -f && vagrant up`
* `vagrant ssh`
* `composer install --prefer-dist`
* `phing`

**Comment by nickschuch** [comment]
WOOOHOOOOOOOO!

**Pull request merged**
