### PR TITLE
Issue #2833318 by benjy, Removed Title module.

### PR DESCRIPTION
**Pull request by benjy**

### CODE REVIEW

**Comment by Sam152** [comment]
lgtm

**Comment by dman-coders** [comment]
SO happy to see title & fences swapped out for Display Suite. 😘

**Comment by benjy** [comment]
We've still got fences for now.

**Comment by dman-coders** [comment]
Aw. I saw it disappear from the third_party_settings and thought it was being eliminated.
https://github.com/previousnext/agov/commit/c9161152630893a97b00c4f25697e20c3268b4f2#diff-426200cde35ad280540891b7d4f79e70L57
Nearly there though!

**Pull request merged**
