### PR TITLE
[#32425] Add d.o sync job with assets for 7.x-3.x.

### PR DESCRIPTION
**Pull request by cafuego**
Do not commit, this depends on https://github.com/previousnext/pnx-ci/pull/25

### CODE REVIEW

**Comment by cafuego** [comment]
test this please

**Comment by cafuego** [comment]
test this please

**Comment by cafuego** [comment]
test this please

**Comment by cafuego** [comment]
test this please

**Comment by kimpepper** [comment]
Is this meant to be _really_ pusing the repo to d.o? Can't see it http://cgit.drupalcode.org/agov/log/?h=7.x-3.x

**Comment by cafuego** [comment]
It won't push until we merge and deploy the associated CI change.

**Comment by cafuego** [comment]
Okay, the CI change is deployed. Once this PR is merged, in theory the job at https://builds.agov.com.au/job/agov_deploy_7x3x/ will sync with drupal.org.

**Comment by kimpepper** [comment]
:pray:

**Pull request merged**
