### PR TITLE
34227 default content

### PR DESCRIPTION
**Pull request by Sam152**

### CODE REVIEW

**Comment by Sam152** [comment]
This is a work in progress because there is a few problems with the FileEntityNormalizer:

* The file data has to be web accessible, we don't have a host for them right now, but I've put an example on imgur.
* They are placed into temporary storage and left there which doesn't work with image derivatives and is generally not a good place to keep files
  * We could normalize the file entity with the file schema information and put it back in the right place (eg, something in public:// would go back into public://), likely a core patch.
  * We could run some kind of post-import to move them from tmp:// to public://.
  * Our own version of FileEntityNormalizer could do whatever we like.

Needs some input.

**Comment by Sam152** [comment]
A few other ideas:

* Default content can fire an event/hook that allows us to move the files into public://
* Default content can be opinionated and assume any files it's importing belong in public://

**Comment by Sam152** [comment]
Would like to get @larowlan's perspective :)

**Comment by larowlan** [comment]
Will look tomorrow

**Comment by larowlan** [comment]
@Sam152 - I discussed this with @rcaracaus a while ago.
If you use https://github.com/md-systems/file_entity with https://github.com/larowlan/default_content - you get a working file solution - file_entity comes with a normalizer for files that exports the file as a base64 encoded blob into the hal+json, and then saves it back to an image on import.
Berdir and md-systems have been using this for their np8 product for at least 12 months.
Given file_entity will more than likely be a key plank in the media initiative and we'll likely want to use entity_embed et al in the future, I think adding it now is worth exploring.
If we don't think that is worth it, we can do one of two things:

* Write our own normalizer (you can copy/paste the one from file_entity and add a service modifier class to wire it in when hal module is enabled, see examples in my blog post or file entity module). This gives us their file normalizer without the rest of the module.
* Contribute to https://www.drupal.org/node/1927648

**Comment by Sam152** [comment]
Will definitely look into file_entity, especially if it's likely to become a fairly standard module.

**Comment by Sam152** [comment]
Cleaned up the history. The normalizer packaged with file_entity worked out of the box.

Exported a standard page and also added agov_default_content to the build:dev target.

**Comment by larowlan** [comment]
Sweeeet

**Pull request merged**
