### PR TITLE
[#32316] swap mandatory with required

### PR DESCRIPTION
**Pull request by kimpepper**

### CODE REVIEW

**Comment by pameeela** [comment]
test this please

**Comment by kimpepper** [comment]
```
Could not locate accessible_forms version 7.x-1.0-alpha2.                [error]
```

**Comment by kimpepper** [comment]
Hmm. Looks like Drupal.org cache needs to be flushed:

`http://updates.drupal.org/release-history/accessible_forms/7.x`

**Comment by kimpepper** [comment]
test this please

**Comment by kimpepper** [comment]
I will re-try this tomorrow. :sleeping:

**Comment by kimpepper** [comment]
test this please

**Pull request merged**
