### PR TITLE
Upgrade pathauto and remove pathauto_persist

### PR DESCRIPTION
**Pull request by kehh**
* pathauto_persist functionality is now incorporated into pathato
* 7.x.2.x branch no longer builds as pathauto_persist is marked as obsolete and the patch does not apply

### CODE REVIEW

**Comment by kehh** [comment]
Oh well looks like that didn't work

**Comment by kimpepper** [comment]
test this please

**Comment by kimpepper** [comment]
@kehh Thanks for the PR.

Probably best to do this against 7.x-3.x and then look at a backport.

**Comment by kehh** [comment]
OK https://www.drupal.org/node/2692583

**Comment by kehh** [comment]
And when I tried to do that it turns out that pathauto is already upgraded on 7.x-3.x. Should I create an issue on d.o. for 7.x-2.x?

**Comment by kimpepper** [comment]
We're only supporting security updates on 7.x-2.x at the moment.

On 23 March 2016 at 13:15, Kehan Harman <notifications@github.com> wrote:

> And when I tried to do that it turns out that pathauto is already upgraded
> on 7.x-3.x. Should I create an issue on d.o. for 7.x-2.x?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/previousnext/agov/pull/777#issuecomment-200134012>
>



-- 
Kim Pepper
Technical Director
PreviousNext

desk: 02 8005 8670
mobile: 0414 212 530
skype: kim.pepper

**Comment by kehh** [comment]
Fair enough

**Pull request closed without merging**
