### PR TITLE
Build system

### PR DESCRIPTION
**Pull request by nickschuch**
What this does:
* Modifies the existing Vagrant image with a PNX official one
* Updates the build file for formatting + generation in the "app" directory instead of outside the projects root.
* Adds Phing to the composer.json
* Implements Phing PHP QA Tools and Behat contrib tasks.

Steps to test:
* Setup a local dev environment as per instructions: https://github.com/previousnext/agov/blob/build-system/README.md#requirements

### CODE REVIEW

**Comment by kimpepper** [comment]
I thought we agreed to use agov-local?

**Comment by nickschuch** [comment]
We did because we didn't think that we could do it in this repository. This work can be moved if you would like.

**Comment by nickschuch** [comment]
Ok, waiting for tests to come back. I think this one is ready for some serious review. I am quite proud how clean the build.xml is now :)

**Comment by kimpepper** [comment]
OK. Let me know if you can get this working in the morning. Planning to
demo tomorrow (around lunchtime)!

On 22 April 2015 at 20:08, Nick Schuch <notifications@github.com> wrote:

> Ok, waiting for tests to come back. I think this one is ready for some
> serious review. I am quite proud how clean the build.xml is now :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/previousnext/agov/pull/461#issuecomment-95170509>.
>



-- 
Kim Pepper
Technical Director
PreviousNext

desk: 02 8005 8670
mobile: 0414 212 530
skype: kim.pepper

**Comment by nickschuch** [comment]
It's just down to the travis.yml file and updating those steps. Ill make changes and watch those builds.

**Pull request merged**
