### PR TITLE
31027 initial style guide

### PR DESCRIPTION
**Pull request by JohnAlbin**
Initial style guide build files.

We should keep all the work in the agov3-style-guide feature branch until the component library is finished.

### CODE REVIEW

**Comment by kimpepper** [comment]
Build is failing on:

```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by JohnAlbin** [comment]
Kim would like me to move the kss-config.json out of the build folder. And move the generated handlebars files into the build folder.

**Comment by JohnAlbin** [comment]
Completed the rearrangement of the build files.

**Comment by nickschuch** [comment]
test this please

**Comment by nickschuch** [comment]
Testing to see if Travis have rolled back yet.

**Comment by kimpepper** [comment]
Still getting errors this morning:

```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by JohnAlbin** [comment]
I just realized we are going to have to add a symlink to /vagrant/styleguide inside app/profiles/agov. It doesn't look like that code is in the agov repo. Does it need to be implemented in the new @nickschuch awesomeness?

**Comment by JohnAlbin** [comment]
Since I'm must merging this into 31027-initial-style-guide, I merging it now.

**Pull request merged**
