### PR TITLE
WIP: Fix symlink path of style guide to work in vagrant and d.o. agov downloads

### PR DESCRIPTION
**Pull request by JohnAlbin**
The style guide is currently broken after we updated our gulpfile.

But this points at an issue about all the symlinks we are using for an agov site. If you download the agov profile from and use it on a fresh D7 core download, the paths are going to be different than if you use phing or vagrant.

To make the gulpfile work in both scenarios, we need to treat the styleguide symlink like all of the other symlinks we create in /profiles/agov/

### CODE REVIEW

**Comment by kimpepper** [comment]
test this please

**Comment by JohnAlbin** [comment]
When the build finishes, the style guide will be found in `profiles/agov/styleguide/agov_whitlam`.

https://agov-pr651.agov.com.au/profiles/agov/styleguide/agov_whitlam/

**Comment by JohnAlbin** [comment]
> https://agov-pr651.agov.com.au/profiles/agov/styleguide/agov_whitlam/index.html

Damn it. :-\

**Comment by kimpepper** [comment]
Page not found. :-(

**Comment by JohnAlbin** [comment]
> $ pnx-ci ssh agov_pr651
> A passage was not created, cannot tunnel to the remote environment

Oh, pnx-ci, you tease.

**Comment by cafuego** [comment]
Have you tired looking for _bike OR shed_ ?

**Comment by JohnAlbin** [comment]
The pnx-ci issue aside (mig showed how I can ssh directly), I think I can guess what is going on here. The symlink is being attempted to be created before the actual directory exists?

**Comment by JohnAlbin** [comment]
Now https://agov-pr651.agov.com.au/profiles/agov/styleguide/agov_whitlam/ is "forbidden". Progress?

**Comment by JohnAlbin** [comment]
test this please

**Comment by JohnAlbin** [comment]
Seeing what happens with a simple update to our `ln` command in `.pnxci.yml`.

**Comment by JohnAlbin** [comment]
@kimpepper https://agov-pr651.agov.com.au/profiles/agov/styleguide/agov_whitlam/ works now.

**Comment by JohnAlbin** [comment]
Testing a simpler shell command in pnxci.yml

**Comment by JohnAlbin** [comment]
Closing in favor of #652

**Pull request closed without merging**
