### PR TITLE
34073 a11y fixes

### PR DESCRIPTION
**Pull request by rikki-iki**
Fixes the following accessibility issues;

* Page title should be the only h1 > remove header h1 (sitename/slogan)
* Add h1 to homepage content
* Visibly hidden elements in the header fail on contrast
* Header Search icon invisible in high contrast mode > use icon font instead of bg image
* Social media link text should be longer > ie "Like us on Facebook" instead of just 'Facebook'
* Publications & News page missing h2 > teaser title tag should be the h2, not a h3. Same for all indexed content except for search results and homepage Latest Updates block
* Search page form missing a label
* Search page title should say 'Search Results'

### CODE REVIEW

**Comment by kimpepper** [comment]
test this please

**Comment by kimpepper** [comment]
Looks like unrelated testbot fails.

```
19:23:27 FATAL: command execution failed
19:23:27 java.io.IOException: Cannot run program "/bin/bash" (in directory "/var/lib/jenkins/jobs/agov_pr/builds/pr732"): error=2, No such file or directory
```

**Comment by rikki-iki** [comment]
test this please

**Comment by rikki-iki** [comment]
@nickschuch @kimpepper the bot failing is my fault, I push new code up before it's finished building the last one, which always seems to break it's brain.

**Comment by kimpepper** [comment]
> Congratulations! No known problems.

**Pull request merged**
