### PR TITLE
[#32941] Styled accessibility checker

### PR DESCRIPTION
**Pull request by ghost**
Steps to test:

When logged in, checker should be styled as follows:

.

Check it is no showing on mobile view.

### CODE REVIEW

**Comment by kimpepper** [comment]
Hmm. I thought the text would be vertical?

**Comment by lena40** [comment]
@kimpepper I thought that might look weird with the checkbox. But can try it.

**Comment by kimpepper** [comment]
Hmm. Unless we just make it a toggle button, and remove the checkbox.

On 27 July 2015 at 15:59, lena40 <notifications@github.com> wrote:

> @kimpepper <https://github.com/kimpepper> I thought that might look weird
> with the checkbox. But can try it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/previousnext/agov/pull/625#issuecomment-125115790>.
>



-- 
Kim Pepper
Technical Director
PreviousNext

desk: 02 8005 8670
mobile: 0414 212 530
skype: kim.pepper

**Comment by nickschuch** [comment]
test this please

**Pull request closed without merging**
