### PR TITLE
34770 main menu

### PR DESCRIPTION
**Pull request by Sam152**
Blocked by #667.

### CODE REVIEW

**Comment by Sam152** [comment]
On a fresh build:dev:

screen shot 2015-09-18 at 5 37 13 pm
screen shot 2015-09-18 at 5 37 17 pm

**Comment by benjy** [comment]
When i login to https://agov-pr672.agov.com.au/ I can't see the menu?

**Comment by Sam152** [comment]
Menu links are added with default content. Enable agov_default_content and it should appear.

**Comment by benjy** [comment]
Do you think agov_default_content should be on by default? Maybe on by default with the new configurable modules PR?

**Comment by Sam152** [comment]
I think configurable and off by default would be good. If we use a build:ci task, we can switch it on for the PR envs which might be better than having it on by default.

**Comment by benjy** [comment]
hmm, if it's off by default then it's going to be a pretty weird experience for non-technical people who come along to spin this up on AWS marketplace or Acquia, the site would just look empty?

**Comment by Sam152** [comment]
If you go through the 7.x-3.x installation, it asks you if you want to enable the default content, but from memory it's a little more obvious than a single checkbox. Perhaps the description of the module in the configurable enable list could indicate that it looks fairly bare without it.

I think the default action for installation should be something aimed at production sites which wouldn't include the default content, or should should provide a way to easily delete it. Perhaps in a follow-up?

**Pull request merged**
