### PR TITLE
[#31055] Add icon library

### PR DESCRIPTION
**Pull request by HierenFeb**
Please review and pull it

### CODE REVIEW

**Comment by JohnAlbin** [comment]
When I went to `@extend` an icon, I ran into some tricky scss-lint issues.

So I've fixed the scss-lint issue and added an example of how to extend one of the fontawesome icons.

**Comment by JohnAlbin** [comment]
Need to make sure the font is loaded. I can do that real quick.

**Comment by JohnAlbin** [comment]
The icon font should now be loading properly. https://agov_pr482.agov.com.au/styleguide/agov_whitlam/section-components.html#kssref-components-icon

**Comment by JohnAlbin** [comment]
Looks like i need to fix a merge conflict.

**Comment by HierenFeb** [comment]
So I have a question now, I see you use new class ".icon-twitter" then extend class ".fa-twitter" in scss.
If anyone want to use other icon, they have to create new class then extend fontawesome class in scss.
Why you don't use fontawesome class (".fa-twitter") in styleguide markup? So we don't need to extend in scss anymore! (easier for builder)

**Comment by JohnAlbin** [comment]
I was seeing this in the generated styles.css file:

```
@font-face{font-family:'FontAwesome';src:url(font-path("font-awesome/fontawesome-webfont.eot"));src:url(font-path("font-awesome/fontawesome-webfont.eot?#iefix")) format("embedded-opentype"),url(font-path("font-awesome/fontawesome-webfont.woff2")) format("woff2"),url(font-path("font-awesome/fontawesome-webfont.woff")) format("woff"),url(font-path("font-awesome/fontawesome-webfont.ttf")) format("truetype"),url(font-path("font-awesome/fontawesome-webfont.svg#fontawesomeregular")) format("svg");font-weight:normal;font-style:normal}.fa{display:inline-block;font:normal normal normal 14px/1 FontAwesome;font-size:inherit;text-rendering:auto;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;transform:translate(0, 0)}.fa-lg{font-size:1.33333em;line-height:0.75em;vertical-align:-15%}
```

Switched to the @import 'font-awesome-compass'; module and removed the _fonts.scss lines and it appears to be working now. Let's see if the icons appear in the PR environement.

**Pull request merged**
